//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApplication.Models.BD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Books
    {
        public int BookID { get; set; }
        public string BookName { get; set; }
        public string Detail { get; set; }
        public double Price { get; set; }
        public string Publication { get; set; }
        public int Quantities { get; set; }
        public string Images { get; set; }
        public int Author_ID { get; set; }
        public int Publisher_ID { get; set; }

        [ForeignKey("Author_ID")]
        public virtual Authors Author { get; set; }
        [ForeignKey("Publisher_ID ")]
        public virtual Publishers Publisher { get; set; }
    }
}
